# Optimization In-Class Exercise

This is a simple exercise for optimizing a scalar valued function.


In [1]:
import numpy as np
import matplotlib.pyplot as plt

Try to a build a simple optimizer to minimize a polynomial:

    f(w) = a[0]*w^d + a[1]*w^(d-1) + ... + a[d]
    

for the coefficients `a = [1,0,-2,0.5,0]`


*  Plot the function f(w)
*  Can you see where the minima is?
*  Write a function that outputs f(w) and its gradient.
*  Test the gradient
*  Run the optimizer on the function to see if it finds the minima.
*  Print the funciton value and number of iterations.
*  Find an initial condition where gradient descent gets stuck at a local minima.

Bonus: Instead of writing the function for a specific coefficient vector a, create a class that works for an arbitrary vector a.
You may wish to use the `np.polyval(a,x)` method to evaluate the polynomial.

In [12]:
k[None,:].shape

(1, 3)

In [10]:
m = np.array([[1,2,3], [3,4,5],[3,1,1]])

k = np.array([4,10,9])

n = m * k[None,:]
print(n)
ans = np.sum(n, axis =1)
print(ans)

[[ 4 20 27]
 [12 40 45]
 [12 10  9]]
[51 97 31]


In [7]:
y = [3,2,5,6]
np.std(y)

1.5811388300841898

In [21]:
(np.mean((y-np.mean(y))**2))

2.5

In [20]:
np.std(y)**2

2.5000000000000004

In [23]:
beta = [1,2,3]


x = [1,2]
import numpy.polynomial.polynomial as poly
poly.polyval(x,beta)

array([ 6., 17.])

In [60]:
m = np.array([1,2,3,4])
m.shape

(4,)

In [61]:
b = np.array([1,2,0])
b.shape

(3,)

In [63]:
diff = m[:,None] - b[None,:]
print(diff.shape)
diff

(4, 3)


array([[ 0, -1,  1],
       [ 1,  0,  2],
       [ 2,  1,  3],
       [ 3,  2,  4]])

In [64]:
diff = diff**2
diff

array([[ 0,  1,  1],
       [ 1,  0,  4],
       [ 4,  1,  9],
       [ 9,  4, 16]])

In [65]:
diff = diff + 1
diff

array([[ 1,  2,  2],
       [ 2,  1,  5],
       [ 5,  2, 10],
       [10,  5, 17]])

In [66]:
a = np.array([1,4,20])

fn = a/ diff

fn

array([[ 1.        ,  2.        , 10.        ],
       [ 0.5       ,  4.        ,  4.        ],
       [ 0.2       ,  2.        ,  2.        ],
       [ 0.1       ,  0.8       ,  1.17647059]])

In [44]:
fn.shape

(4, 1, 1, 3)

In [72]:
fn

array([[ 1.        ,  2.        , 10.        ],
       [ 0.5       ,  4.        ,  4.        ],
       [ 0.2       ,  2.        ,  2.        ],
       [ 0.1       ,  0.8       ,  1.17647059]])

In [75]:
v = fn.dot(b)
v

array([5. , 8.5, 4.2, 1.7])

In [76]:
m = np.array([1,2])
n = np.array([1,3])

b = m.dot(n)

In [77]:
b

7

In [82]:
np.hstack((1,2))

array([1, 2])