# LASSO Regression In-Class Exercise

In this exercise, we will see how to use LASSO for pitch detection and noise removal in audio.

We load the following packages.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pickle

## Load the Data

The data is taken from a sample of about 20 ms of audio from a viola.  I have already pre-processed the data.  You can load it with the following command.  The value `t` is the time (in seconds) and `y` is the sample of audio (this is a mono recording).  Noise has been artificially added to the sample.

In [10]:
fn_src = 'https://raw.githubusercontent.com/sdrangan/introml/master/unit05_lasso/viola_sample.p'
fn_dst = 'viola_sample.p'

import os
from six.moves import urllib

if os.path.isfile(fn_dst):
    print('File %s is already downloaded' % fn_dst)
else:        
    urllib.request.urlretrieve(fn_src, fn_dst)
    print('File %s downloaded' % fn_dst)

with open(fn_dst,'rb') as fp:
    t,y = pickle.load(fp)

File viola_sample.p is already downloaded


Plot the data `y` vs. `t`.  

In [5]:
# TODO

## Creating Features for a Sinusoidal Model

We will try to fit a model of the form:

    y[i] = \sum_j a[j]*sin(2*pi*freq[j]*t[i]) + b[j]*cos(2*pi*freq[j]*t[i])

That is, `y[i]` is a sum of sinusoids.  This is a common model for audio signals since an instrument, such as a viola, produces discrete tones.  

This model is non-linear in the frequency parameters.  So, instead of trying to find the frequencies, we will fix a large number of frequencies and then require that the coefficients `a[j]` and `b[j]` are mostly sparse.  

We will use the following vector of frequencies.  This vector includes frequencies on the muscial scale as well as frequencies between the musical notes.

In [6]:
freq = 55*2**(np.arange(5*96)/96)

To fit the sinusoidal model, we will write a function to map the values `t` to 
the `sin` and `cos` features.  Finish the function `transform` that creates matrices:

    Xcos[i,j] = np.cos(2*np.pi*t[i]*freq[j])
    Xsin[i,j] = np.sin(2*np.pi*t[i]*freq[j])
    X = np.hstack((Xcos,Xsin))
    
So, if `freq` is length `d`, there will `2*d` features.  You can try to create the matrices using python broadcasting if you want to avoid a for loop.    

In [104]:
def transform(t,freq):
    # TODO
    # Xcos = ...
    # Xsin = ...
    
    X = np.hstack((Xcos,Xsin))    
    return X

Split the data `t` and `y` into training and test.  Use approximately 50% for each set.

In [105]:
from sklearn.model_selection import train_test_split

# TODO
# ttr, tts, ytr, yts = train_test_split(...)

Transform the `ttr`, `tts` into `Xtr` and `Xts`.

In [8]:
# TODO

## Use LASSO to Find the Frequencies

We can now use LASSO regression to find the model
* Use LASSO regression with `alpha=500` to fit the model.  
* Find the R^2-score on the test data.
* Plot the predicted value of `y` for `t in [0,0.02]`.

In [107]:
from sklearn.linear_model import Lasso

# TODO
# regr = Lasso(...)

Recall that you can find the coefficient in the model via `w = regr.coef_`.  If `freq` has `d` terms, then `w` will have `2*d` terms.
* Split the coefficients `w` into `a` and `b`, the terms for the `cos` and `sin` features.
* Plot `a` and `b` using `plt.stem`.
* Which frequencies is dominant in this track?


In [9]:
# TODO

Still have time...
* Find the optimal `alpha` using cross-validation

In [25]:
import numpy as np
X = np.random.rand(100,20)
print(X)
features = X.shape
print(features)



[[0.13765578 0.47510883 0.95738653 ... 0.02395681 0.70744079 0.85743281]
 [0.36421119 0.36564856 0.41310096 ... 0.9490035  0.8333967  0.2318226 ]
 [0.83264481 0.09996197 0.48908869 ... 0.53602375 0.47003249 0.80156745]
 ...
 [0.04807133 0.38238786 0.42597839 ... 0.53061292 0.66869412 0.06087322]
 [0.34555268 0.14044854 0.84313909 ... 0.49006401 0.97600521 0.67301616]
 [0.16665389 0.30336382 0.07396954 ... 0.10518943 0.59950146 0.3604516 ]]
(100, 20)


In [26]:
n = np.zeros((100,2))
n.shape

(100, 2)

In [37]:
print(X[:,0:1])

[[0.13765578]
 [0.36421119]
 [0.83264481]
 [0.03047989]
 [0.30269582]
 [0.34470141]
 [0.42982824]
 [0.14868668]
 [0.71506055]
 [0.51532239]
 [0.09634308]
 [0.14455217]
 [0.64537754]
 [0.20716688]
 [0.23082338]
 [0.17629911]
 [0.64227189]
 [0.63792674]
 [0.75168914]
 [0.66737009]
 [0.47581783]
 [0.7845188 ]
 [0.85287189]
 [0.66444092]
 [0.57930172]
 [0.08680832]
 [0.49466057]
 [0.7791988 ]
 [0.75968031]
 [0.67664938]
 [0.06082723]
 [0.31276755]
 [0.19545772]
 [0.4258644 ]
 [0.10998838]
 [0.50683128]
 [0.6610144 ]
 [0.80648973]
 [0.56091701]
 [0.7155594 ]
 [0.18752875]
 [0.75800355]
 [0.79849896]
 [0.80657627]
 [0.85974146]
 [0.42719382]
 [0.88685244]
 [0.55170407]
 [0.63205507]
 [0.66193539]
 [0.4520089 ]
 [0.03023347]
 [0.49121856]
 [0.97781655]
 [0.77642495]
 [0.33280743]
 [0.4238546 ]
 [0.4044056 ]
 [0.83416106]
 [0.72560431]
 [0.36808621]
 [0.76802885]
 [0.98571587]
 [0.17516988]
 [0.53582589]
 [0.94085348]
 [0.74712655]
 [0.99252141]
 [0.53939307]
 [0.39885913]
 [0.05017784]
 [0.00

In [27]:
X[:,0:1].shape

(100, 1)

In [31]:
n[:,0:1] = X[:,0:1]
n[:,1:2] = X[:,1:2]



In [35]:
Xtrsliced = np.zeros((100,2))
Xtrsliced = np.zeros((100,2))
for i in range(0,20):
    Xtrsliced[:,0:1] = X[:,i:i+1]
    for j in range(i+1, 20):
        Xtrsliced[:,1:2] = X[:,j:j+1]
        print(i, j)

0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
0 10
0 11
0 12
0 13
0 14
0 15
0 16
0 17
0 18
0 19
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10
1 11
1 12
1 13
1 14
1 15
1 16
1 17
1 18
1 19
2 3
2 4
2 5
2 6
2 7
2 8
2 9
2 10
2 11
2 12
2 13
2 14
2 15
2 16
2 17
2 18
2 19
3 4
3 5
3 6
3 7
3 8
3 9
3 10
3 11
3 12
3 13
3 14
3 15
3 16
3 17
3 18
3 19
4 5
4 6
4 7
4 8
4 9
4 10
4 11
4 12
4 13
4 14
4 15
4 16
4 17
4 18
4 19
5 6
5 7
5 8
5 9
5 10
5 11
5 12
5 13
5 14
5 15
5 16
5 17
5 18
5 19
6 7
6 8
6 9
6 10
6 11
6 12
6 13
6 14
6 15
6 16
6 17
6 18
6 19
7 8
7 9
7 10
7 11
7 12
7 13
7 14
7 15
7 16
7 17
7 18
7 19
8 9
8 10
8 11
8 12
8 13
8 14
8 15
8 16
8 17
8 18
8 19
9 10
9 11
9 12
9 13
9 14
9 15
9 16
9 17
9 18
9 19
10 11
10 12
10 13
10 14
10 15
10 16
10 17
10 18
10 19
11 12
11 13
11 14
11 15
11 16
11 17
11 18
11 19
12 13
12 14
12 15
12 16
12 17
12 18
12 19
13 14
13 15
13 16
13 17
13 18
13 19
14 15
14 16
14 17
14 18
14 19
15 16
15 17
15 18
15 19
16 17
16 18
16 19
17 18
17 19
18 19


[[0.85743281 0.85743281]
 [0.2318226  0.2318226 ]
 [0.80156745 0.80156745]
 [0.10704441 0.10704441]
 [0.57227439 0.57227439]
 [0.24963989 0.24963989]
 [0.196957   0.196957  ]
 [0.38863793 0.38863793]
 [0.44702072 0.44702072]
 [0.03393883 0.03393883]
 [0.16908534 0.16908534]
 [0.88440704 0.88440704]
 [0.49348939 0.49348939]
 [0.03698334 0.03698334]
 [0.78551303 0.78551303]
 [0.582988   0.582988  ]
 [0.36437778 0.36437778]
 [0.14522425 0.14522425]
 [0.85489466 0.85489466]
 [0.98062976 0.98062976]
 [0.81361352 0.81361352]
 [0.99151572 0.99151572]
 [0.81430784 0.81430784]
 [0.03538315 0.03538315]
 [0.59411925 0.59411925]
 [0.01839164 0.01839164]
 [0.24856267 0.24856267]
 [0.96738167 0.96738167]
 [0.13424602 0.13424602]
 [0.58750739 0.58750739]
 [0.59304746 0.59304746]
 [0.73782546 0.73782546]
 [0.53251871 0.53251871]
 [0.01325362 0.01325362]
 [0.16565782 0.16565782]
 [0.25314362 0.25314362]
 [0.79494967 0.79494967]
 [0.87350211 0.87350211]
 [0.44905982 0.44905982]
 [0.82976526 0.82976526]


In [51]:
k = np.zeros((4,2))
k[:,0] = X[:,0]
print(k.shape)
k[:,1] = X[:,1]
print(k.shape)
print(k)
print(y)
model.fit(k, y)

(4, 2)
(4, 2)
[[0.98717682 0.50287527]
 [0.30834324 0.91575341]
 [0.95504538 0.70373145]
 [0.87209463 0.28072958]]
[0.68975139 0.85143247 0.42548131 0.11543432]


LinearRegression()

In [54]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

score = -1
best_model = None

for i in range(0,features):
    X_sliced = X[:,i,None]
    Xtr, Xts, ytr, yts = train_test_split(X_sliced,y,test_size=0.33,shuffle=True)
    model = LinearRegression()
    model.fit(Xtr, ytr)
    yhat = model.predict(Xts)
    rsq = r2_score(yts, yhat)
    if rsq > score:
        score = rsq 
        best_model = model
        
        
    
    


In [55]:
Xtr_sliced = np.zeros((Xtr.shape[0], 2))
Xts_sliced = np.zeros((Xts.shape[0], 2))
features = Xtr.shape[1]

for i in range(0,features):
    Xtr_sliced[:,0] = Xtr[:,i]
    Xtr_sliced[:,0] = Xts[:,i]
    for j in range(i+1, features):
        Xtr_sliced[:,1] = Xtr[:,j]
        Xts_sliced[:,1] = Xts[:,j]
        model = LinearRegression()
        model.fit(Xtr_sliced, ytr)
        yhat = model.predict(Xts_sliced)
        rsq = r2_score(yts, yhat)
        if rsq > score:
            score = rsq 
            best_model = model
        
        

In [64]:
X = [[1,2,3],[3,4,5],[1,1,3]]
y = np.mean(X,axis = 1, keepdims=True)
print(y)

[[2.        ]
 [4.        ]
 [1.66666667]]


In [65]:
print(X-y)

print(n)
print((X-y)/n)

[[-1.          0.          1.        ]
 [-1.          0.          1.        ]
 [-0.66666667 -0.66666667  1.33333333]]
[[0.81649658]
 [0.81649658]
 [0.94280904]]
[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-0.70710678 -0.70710678  1.41421356]]


In [66]:
n = (X-np.mean(X,axis = 1, keepdims=True))/np.std(X, axis =1, keepdims=True)
print(n)

[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-0.70710678 -0.70710678  1.41421356]]


In [69]:
def normalize(X, ax):
    std_ = np.std(X, axis =ax, keepdims=True)
    Z = (X-np.mean(X,axis = ax, keepdims=True))/std_
    return Z 

def fit(Xtr, Xts, ytr, yts):
    
    Xtr_normalised = normalize(Xtr,1)
    ytr_normalised = normalize(ytr,0)
    
    model = LinearRegression()
    model.fit(Xtr_normalised, ytr_normalised)
    
    Xts_normalised = normalize(Xts,1)
    yts_normalised = normalize(yts,0)
    
    yhat = model.predict(Xts_normalised)
    Rss = np.sum((yhat-yts)**2)
    print("The RSS is ", Rss)
    

    

In [83]:
def normalize(X, ax):
    std_ = np.std(X, axis =ax, keepdims=True)
    Z = (X-np.mean(X,axis = ax, keepdims=True))/std_
    return Z 

a = np.array([1,2,3,4,5])
# a= a.reshape(-1,1)
ytr = a
m =(ytr - np.mean(ytr))/np.std(ytr)

In [84]:
print(m)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [88]:
from sklearn.linear_model import Lasso

def lasso_fit(xtr, xts, ytr, yts, a, b, lam):
    
    model = Lasso(alpha=lam)
    
    #Todo 1 p =100
    alpha_range = np.random.uniform(a,b+1,100)
    phi_tr = np.exp(-xtr[:,None]*alpha_range[None,:])
    phi_ts = np.exp(-xts[:,None]*alpha_range[None,:])
    
    #Todo 2, fit the model
    model.fit(phi_tr, ytr)
    
    #Todo 3, Test error
    yhat = model.predict(phi_ts)
    mse_test = np.mean((yhat-yts)**2)
    print("the test error is ", mse_test)
    
    #Todo 4, Calculate alpha and beta
    model_coeff = model.coef_
    sorted_coeff = np.argsort(model_coeff)
    index = sorted_coeff[3]
    beta_3 = model_coeff[index]
    alpha_3 = alpha_range[index]
    
    print("beta = {:2f} and alpha = {:2f} for k = 3".format(beta_3, alpha_3))
    
    
    
lasso_fit(xtr, xts, ytr, yts, a, b, lam)
    
    
    